// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJJYc0wZP4nPqOegjbgn-7amTdkhlhhQ',
    appId: '1:696035472864:android:3d39acb77ea7db701ae785',
    messagingSenderId: '696035472864',
    projectId: 'shoutout-dev-46c81',
    storageBucket: 'shoutout-dev-46c81.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrovF4JyX3YSRq-ZRvZ0ra264emHUC1sU',
    appId: '1:696035472864:ios:546e2af48292ea4d1ae785',
    messagingSenderId: '696035472864',
    projectId: 'shoutout-dev-46c81',
    storageBucket: 'shoutout-dev-46c81.firebasestorage.app',
    iosClientId:
        '696035472864-1ior5ej6dh5idn77mp5kukp1itpgs74f.apps.googleusercontent.com',
    iosBundleId: 'cz.shoutout.app.dev',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcieaTn_wC-0tB2Y3gVCtD7dj9lINSJs',
    appId: '1:696035472864:web:744f27eac9135ba91ae785',
    messagingSenderId: '696035472864',
    projectId: 'shoutout-dev-46c81',
    authDomain: 'shoutout-dev-46c81.firebaseapp.com',
    storageBucket: 'shoutout-dev-46c81.firebasestorage.app',
  );
}
